# Configuration file for `prek`, a git hook framework written in Rust.
# See https://prek.j178.dev for more information.
#:schema https://www.schemastore.org/prek.json

[[repos]]
repo  = "https://github.com/pre-commit/pre-commit-hooks"
rev   = "3e8a8703264a2f4a69428a0aa4dcb512790b2c8c"
hooks = [
  { id = "trailing-whitespace" },
  { id = "end-of-file-fixer" },
  { id = "check-yaml" },
  { id = "check-json" },
  { id = "check-merge-conflict" },
  { id = "check-added-large-files", exclude = "(?x).png" }
]

[[repos]]
repo  = "https://github.com/tombi-toml/tombi-pre-commit"
rev   = "5421ca8ca3d6a659b6c097512b486395676a6af1"
hooks = [{ id = "tombi-format" }, { id = "tombi-lint" }]

[[repos]]
repo  = "https://github.com/rhysd/actionlint"
rev   = "914e7df21a07ef503a81201c76d2b11c789d3fca"
hooks = [{ id = "actionlint" }]

[[repos]]
repo  = "https://github.com/google/yamlfmt"
rev   = "21ca5323a9c87ee37a434e0ca908efc0a89daa07"
hooks = [{ id = "yamlfmt" }]

[[repos]]
repo  = "https://github.com/zizmorcore/zizmor-pre-commit"
rev   = "067260dc5fe6ea86b7551bfd6f8b3ba4e6c93129"
hooks = [
  {
    id             = "zizmor",
    pass_filenames = false,
    args           = ["--no-progress", ".github"]
  }
]

[[repos]]
repo  = "https://github.com/doublify/pre-commit-rust"
rev   = "eeee35a89e69d5772bdee97db1a6a898467b686e"
hooks = [
  { id = "fmt" },
  { id = "clippy", args = ["--all-features", "--", "-D", "warnings"] }
]

[[repos]]
repo  = "https://github.com/compilerla/conventional-pre-commit"
rev   = "91ab4bf57e58b32adf1a122681f6ebe164d081c8"
hooks = [{ id = "conventional-pre-commit", stages = ["commit-msg"] }]
