# pets: package=tmux
# pets: symlink=~/.tmux.conf

set -g default-terminal "tmux-256color"
set -g history-limit 30000
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
